/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u07449294150
 */
public class JFrmJavMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrmJavMenu
     */
    public JFrmJavMenu() {
        initComponents();
        setTitle("Loja de VídeoGame");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuJavUsuario = new javax.swing.JMenuItem();
        jMnuJavCliente = new javax.swing.JMenuItem();
        jMnuJavFornecedor = new javax.swing.JMenuItem();
        jMnuJavVendedor = new javax.swing.JMenuItem();
        jMnuJavProduto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMnuJavSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnuJavVenda = new javax.swing.JMenuItem();
        jMnuJavCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setMnemonic('c');
        jMenu1.setText("Cadastro");

        jMnuJavUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuJavUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/usuario.png"))); // NOI18N
        jMnuJavUsuario.setMnemonic('u');
        jMnuJavUsuario.setText("Usuario");
        jMnuJavUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuJavUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuJavUsuario);

        jMnuJavCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuJavCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/cliente.png"))); // NOI18N
        jMnuJavCliente.setMnemonic('c');
        jMnuJavCliente.setText("Cliente");
        jMenu1.add(jMnuJavCliente);

        jMnuJavFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuJavFornecedor.setMnemonic('f');
        jMnuJavFornecedor.setText("Fornecedor");
        jMenu1.add(jMnuJavFornecedor);

        jMnuJavVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuJavVendedor.setMnemonic('v');
        jMnuJavVendedor.setText("Vendedor");
        jMnuJavVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuJavVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuJavVendedor);

        jMnuJavProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuJavProduto.setMnemonic('p');
        jMnuJavProduto.setText("Produto");
        jMnuJavProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuJavProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuJavProduto);
        jMenu1.add(jSeparator2);

        jMnuJavSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuJavSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/exit.png"))); // NOI18N
        jMnuJavSair.setMnemonic('s');
        jMnuJavSair.setText("Sair");
        jMenu1.add(jMnuJavSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimentos");

        jMnuJavVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuJavVenda.setMnemonic('v');
        jMnuJavVenda.setText("Venda");
        jMenu2.add(jMnuJavVenda);

        jMnuJavCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuJavCompra.setMnemonic('v');
        jMnuJavCompra.setText("Compra");
        jMenu2.add(jMnuJavCompra);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuJavUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuJavUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgJavUsuarios jDlgJavUsuarios = new JDlgJavUsuarios(null, true);
        jDlgJavUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuJavUsuarioActionPerformed

    private void jMnuJavVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuJavVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuJavVendedorActionPerformed

    private void jMnuJavProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuJavProdutoActionPerformed
        // TODO add your handling code here:
        JDlgJavProduto jDlgJavProduto = new JDlgJavProduto(null, true);
        jDlgJavProduto.setVisible(true);
    }//GEN-LAST:event_jMnuJavProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmJavMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmJavMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmJavMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmJavMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmJavMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuJavCliente;
    private javax.swing.JMenuItem jMnuJavCompra;
    private javax.swing.JMenuItem jMnuJavFornecedor;
    private javax.swing.JMenuItem jMnuJavProduto;
    private javax.swing.JMenuItem jMnuJavSair;
    private javax.swing.JMenuItem jMnuJavUsuario;
    private javax.swing.JMenuItem jMnuJavVenda;
    private javax.swing.JMenuItem jMnuJavVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
